// src/app/loan-form/screens/initial-form/initial-form.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-initial-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <form (ngSubmit)="handleSubmit()" class="space-y-6">
      <div class="space-y-2">
        <label for="employer" class="text-sm font-medium">Select employer</label>
        <select id="employer" [(ngModel)]="employer" name="employer" required class="w-full border p-2 rounded">
          <option value="" disabled selected>Select employer</option>
          <option value="employer1">Employer 1</option>
          <option value="employer2">Employer 2</option>
          <option value="employer3">Employer 3</option>
        </select>
      </div>

      <div class="space-y-2">
        <label for="amount" class="text-sm font-medium">Enter amount</label>
        <input id="amount" name="amount" type="text" [(ngModel)]="amount" placeholder="Enter amount" required class="w-full border p-2 rounded" />
      </div>

      <div class="space-y-2">
        <label for="duration" class="text-sm font-medium">Duration</label>
        <select id="duration" [(ngModel)]="duration" name="duration" required class="w-full border p-2 rounded">
          <option value="" disabled selected>Select duration</option>
          <option value="1">1 Month</option>
          <option value="3">3 Months</option>
          <option value="6">6 Months</option>
          <option value="12">12 Months</option>
        </select>
      </div>

      <button type="submit" class="bg-blue-700 hover:bg-blue-800 text-white p-2 rounded w-full">
        Continue
      </button>
    </form>
  `,
})
export class InitialFormComponent {
  employer: string = '';
  amount: string = '';
  duration: string = '';

  @Output() next = new EventEmitter<Partial<{ employer: string; amount: string; duration: string }>>();

  handleSubmit() {
    this.next.emit({
      employer: this.employer,
      amount: this.amount,
      duration: this.duration,
    });
  }
}

// src/components/form/screens/initial-form.tsx
"use client"

import type React from "react"

import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import type { LoanFormData } from "../types"

interface InitialFormProps {
  onNext: (data: Partial<LoanFormData>) => void
}

export function InitialForm({ onNext }: InitialFormProps) {
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    const formData = new FormData(e.target as HTMLFormElement)
    onNext({
      employer: formData.get("employer") as string,
      amount: formData.get("amount") as string,
      duration: formData.get("duration") as string,
    })
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="space-y-2">
        <label htmlFor="employer" className="text-sm font-medium">
          Select employer
        </label>
        <Select name="employer" required>
          <SelectTrigger id="employer">
            <SelectValue placeholder="Select employer" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="employer1">Employer 1</SelectItem>
            <SelectItem value="employer2">Employer 2</SelectItem>
            <SelectItem value="employer3">Employer 3</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="space-y-2">
        <label htmlFor="amount" className="text-sm font-medium">
          Enter amount
        </label>
        <Input id="amount" name="amount" type="text" placeholder="Enter amount" required />
      </div>

      <div className="space-y-2">
        <label htmlFor="duration" className="text-sm font-medium">
          Duration
        </label>
        <Select name="duration" required>
          <SelectTrigger id="duration">
            <SelectValue placeholder="Select duration" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="1">1 Month</SelectItem>
            <SelectItem value="3">3 Months</SelectItem>
            <SelectItem value="6">6 Months</SelectItem>
            <SelectItem value="12">12 Months</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <Button type="submit" className="w-full bg-blue-700 hover:bg-blue-800">
        Continue
      </Button>
    </form>
  )
}
